require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Dadio' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'rn-range-slider', :path => '../node_modules/rn-range-slider'


  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'


  pod 'react-native-razorpay', :path => '../node_modules/react-native-razorpay'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'


  pod 'RNNotificationBanner', :path => '../node_modules/react-native-notification-banner'

  pod 'RNCallKeep', :path => '../node_modules/react-native-callkeep'



  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  pod 'RNEnxRtc', :path => '../node_modules/enx-rtc-react-native'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  target 'DadioTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Dadio-tvOS' do
  # Pods for Dadio-tvOS

  target 'Dadio-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
